apiVersion: v1
kind: Pod
metadata:
  name: pg-pod
  labels:
    app: pg-pod
spec:
  containers:
  - name: postgresql
    image: postgres:10.13
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
